### ISSUE TITLE
오늘의 길 ERDiagram을 설계한다

### ISSUE THREAD

**Issue by hyohyo12** [boostcampwm-2024/web09-DailyRoad#11]
### ✨ Describe

회원, 지도, 코스, 리뷰 등 여러 정보를 저장하기위한 ERD 설계

### ✅ Tasks

- [ ] 회원 테이블 설계
- [ ] 지도 테이블 설계
- [ ] 코스 테이블 설계
- [ ] 리뷰 테이블 설계
- [ ] 구독 테이블 설계

### 🕰️ Estimated Time of Completion

4 - 5

### 🙋🏻 More

바로 진행하지 않는 기능들에 대해서도 설계를 해두자!
