### ISSUE TITLE
ElasticSearch를 이용하여 NestJS 검색기능을 업그레이드 한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#138]
### ✨ Describe

`ElasticSearch`를 이용하여 `NestJS` 검색기능을 업그레이드 한다

### ✅ Tasks

 - [ ] `ElasticSearch` 환경 구축
 - [ ] `place` 검색 기능 적용
 - [ ] 주기적으로 데이터 이전 배치 구현

### 🕰️ Estimated Time of Completion

24

**Comment by Miensoap** [comment]
스토리지 100gb 로 설정해둬서,  같은 인스턴스 사용해도 될 것 같아요.
