### ISSUE TITLE
구글 장소 데이터를 수집하고 가공하여 DB에 저장한다

### ISSUE THREAD

**Issue by Miensoap** [boostcampwm-2024/web09-DailyRoad#152]
### ✨ Describe

구글 장소 데이터를 수집하고 가공하여 DB에 저장한다

### ✅ Tasks

- [x] 구글 장소 데이터 수집
- [x] 구글 장소 썸네일 데이터 수집
- [x] import 가능한 형태로 포맷팅
  - [x]  Mysql
  - [x] ElasticSearch

### 🕰️ Estimated Time of Completion

6H
