### ISSUE TITLE
구글 장소 검색 기능과 새 장소 등록시 썸네일 요청을 추가한다.

### ISSUE THREAD

**Issue by Miensoap** [boostcampwm-2024/web09-DailyRoad#154]
### ✨ Describe

구글 장소 검색 기능과 새 장소 추가시 썸네일 요청을 추가한다.

### ✅ Tasks

- [x] 구글 장소 검색 API
- [x] 새 장소 등록시 썸네일 요청
- [x] 이미 등록된 장소일 경우 처리

### 🕰️ Estimated Time of Completion

4H
