### ISSUE TITLE
간편 구글 로그인 기능을 구현한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#8]
### ✨ Describe

간편 로그인

### ✅ Tasks

- [ ] 네이버 Developer 등록
- [ ] OAuth 코드 작성
- [ ] 사용자 데이터 저장

### 🕰️ Estimated Time of Completion

10.5시간

### 🙋🏻 More

다양한 소셜로그인 지원을 위한 확장성을 고려하며 구현하기
### 참고링크
- [네이버 로그인 개발가이드](https://developers.naver.com/docs/login/devguide/devguide.md)
