### ISSUE TITLE
장소에 색상 칼럼을 추가한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#86]
### ✨ Describe

- 장소에 색상 칼럼 추가 (color)
  - 색상 종류
    - `RED`
    - `ORANGE`
    - `YELLOW`
    - `GREEN`
    - `BLUE`
    - `PURPLE`

### ✅ Tasks

- [x] `Color` `enum` 만들기
- [x] 색상 칼럼 추가
- [x] `Place` DDL 수정

### 🕰️ Estimated Time of Completion

1
