### ISSUE TITLE
이미지 업로드 API 구현한다

### ISSUE THREAD

**Issue by hyohyo12** [boostcampwm-2024/web09-DailyRoad#88]
### ✨ Describe

- 프론트에서 이미지를 리사이징 후 스토리지에 `pre-signed url` 요청 후 스토리지에 이미지 전달 후 받은 이미지 url 을 포함한 지도 및 코스를 백엔드 서버로 전달

### ✅ Tasks

- [ ] 리사이징된 이미지 전달받기
- [ ] 스토리지 서버로 이미지 저장 요청
- [ ] 프론트가 사용할 함수 작성
  - [ ] pre-signed url 을 스토리지 서버로 `axios` 요청 보내기
  - [ ] 받은 url 에 사진 전달
  - [ ] 리턴은 스토리지에서 받은 사진 url

### 🕰️ Estimated Time of Completion

4.5
