### ISSUE TITLE
코스 순서 저장 방식을 개선한다

### ISSUE THREAD

**Issue by koomchang** [boostcampwm-2024/web09-DailyRoad#90]
### ✨ Describe

- 코스 순서의 저장 방식을 개선한다
  - `NoSQL` 혹은 테이블 구조 변경

### ✅ Tasks

- [x] 각 순서 저장 방식 성능 실험
  - [x] 기존 Single PUT
  - [x] Bulk 쿼리로 PUT
  - [x] Linked List
  - [x] LexoRank

- [x] 새 방법 적용
  - [x] 적용 후 성능 테스트 

### 🕰️ Estimated Time of Completion

12

**Comment by Miensoap** [comment]
https://languid-pluto-1b6.notion.site/143d612fb50c800398f0cfdad29e0914

**Comment by Miensoap** [comment]
### Linked List 방식 시도 
1. 새 Linked List 를 만들어 `Course` 의 `CoursePlace` 배열을 대체해 저장
-> 기존의 방식과 차이가 보이지 않음.

2. 변경된 부분만 prev 업데이트 하여 저장
-> 중간에 새 장소가 추가되는 경우 처리 불가

### Bulk 쿼리 이용한 PUT 방식
- `CoursePlace` 에 대한 레포지토리 사용
- bulk 쿼리로 코스에 추가된 장소들 모두 삭제 -> 새 배열 삽입 두 번의 쿼리 사용

### 추가 실험
1. 업데이트 전 장소 유효성 검사는 비동기적 select 문을 실행하기 때문에 전체 성능에 크게 영향을 미치지 않는다.
2. 업데이트 후 장소 정보 조회 또한 비동기적으로 실행되어 전체 성은에 크게 영향을 미치지 않는다.

### 결론
기존 PUT 방식을 개선한 Bulk 쿼리 이용한 방식 사용.

**1200~1500ms** -> **200~300ms** 로 **81.48%** 가량 처리 시간 감소

기존 대비 **18.52%** 의 시간 소요
평균 **1100ms**의 속도 개선 달성
